# Generated by Django 2.2.5 on 2019-09-10 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bidder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.IntegerField(default=0)),
                ('status', models.CharField(default='Set', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ipo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_price', models.IntegerField(default=0)),
                ('ipo_count', models.IntegerField(default=0)),
                ('status', models.CharField(default='Open', max_length=20)),
                ('player', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='player.Player')),
            ],
        ),
    ]
