# Generated by Django 2.2.5 on 2019-09-11 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipo', '0002_auto_20190910_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipo',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='player.Player'),
        ),
    ]
