# Generated by Django 2.2.5 on 2019-09-11 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipo', '0004_auto_20190911_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidder',
            name='bidder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
