# Generated by Django 2.2.5 on 2019-09-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipo', '0007_bidder_value_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidder',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='bidder',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
