# Generated by Django 2.2.5 on 2019-09-10 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.IntegerField(default=0)),
                ('status', models.CharField(default='Set', max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.IntegerField(default=0)),
                ('status', models.CharField(default='Set', max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('player', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='player.Player')),
            ],
        ),
        migrations.CreateModel(
            name='SuccessTrade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.IntegerField(default=0)),
                ('ask', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trade.Ask')),
                ('bid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trade.Bid')),
            ],
        ),
    ]
