# Generated by Django 2.2.5 on 2019-09-12 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
        ('trade', '0002_auto_20190910_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ask',
            name='trade',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='trade',
        ),
        migrations.AddField(
            model_name='ask',
            name='player',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='player.Player'),
        ),
        migrations.AddField(
            model_name='bid',
            name='player',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='player.Player'),
        ),
    ]
