# Generated by Django 2.2.5 on 2019-09-12 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_auto_20190912_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='player.Player'),
        ),
    ]
