# Generated by Django 2.2.5 on 2019-09-13 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_auto_20190912_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='value_actual',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bid',
            name='value_last',
            field=models.IntegerField(default=0),
        ),
    ]
