# Generated by Django 2.2.5 on 2019-09-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0006_auto_20190913_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
