# Generated by Django 2.2.5 on 2019-09-10 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('surname', models.CharField(max_length=120)),
                ('age', models.CharField(max_length=120)),
                ('price_actual', models.IntegerField(default=1)),
                ('price_last', models.IntegerField(default=1)),
                ('price_theorical', models.IntegerField(default=1)),
                ('pool', models.IntegerField(default=1)),
                ('rating', models.CharField(default='100%', max_length=120)),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='player.Team')),
            ],
        ),
    ]
