# Generated by Django 2.2.5 on 2019-09-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='ipo_last',
            field=models.IntegerField(default=0),
        ),
    ]
