# Generated by Django 2.2.5 on 2019-09-12 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20190911_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='compromised',
            field=models.IntegerField(default=0),
        ),
    ]
